# Generated by Django 5.2.7 on 2025-11-02 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_empresa_user_facultad_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calificacion', models.CharField(choices=[('comportamiento', 'Comportamiento'), ('proyecto', 'Proyecto')], max_length=20)),
                ('quimestre', models.CharField(choices=[('Q1', 'Quimestre 1'), ('Q2', 'Quimestre 2')], max_length=2)),
                ('periodo', models.CharField(choices=[('P1', 'Período 1'), ('P2', 'Período 2'), ('P3', 'Período 3')], max_length=2)),
                ('valor', models.CharField(max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='inscripciones.inscripcion')),
                ('inscripcion_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='inscripciones.inscripcioninterna')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['quimestre', 'periodo', 'tipo_calificacion'],
                'unique_together': {('inscripcion', 'inscripcion_interna', 'tipo_calificacion', 'quimestre', 'periodo')},
            },
        ),
    ]
